// Auto-generated by Wallust
// DO NOT EDIT MANUALLY
import QtQuick

QtObject {{
    // Background colors
    readonly property color background: "{background}"
    readonly property color backgroundAlt: "{color0}"
    
    // Foreground colors
    readonly property color foreground: "{foreground}"
    readonly property color foregroundAlt: "{color7}"
    
    // Accent colors (from palette)
    readonly property color accent: "{color4}"      // Blue-ish
    readonly property color accentAlt: "{color5}"   // Purple-ish
    
    // Status colors
    readonly property color urgent: "{color1}"      // Red
    readonly property color success: "{color2}"     // Green
    readonly property color warning: "{color3}"     // Yellow
    
    // Additional palette colors
    readonly property color color0: "{color0}"
    readonly property color color1: "{color1}"
    readonly property color color2: "{color2}"
    readonly property color color3: "{color3}"
    readonly property color color4: "{color4}"
    readonly property color color5: "{color5}"
    readonly property color color6: "{color6}"
    readonly property color color7: "{color7}"
    readonly property color color8: "{color8}"
    readonly property color color9: "{color9}"
    readonly property color color10: "{color10}"
    readonly property color color11: "{color11}"
    readonly property color color12: "{color12}"
    readonly property color color13: "{color13}"
    readonly property color color14: "{color14}"
    readonly property color color15: "{color15}"
}}
